# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Vivado/Projects/ee2020_with_vga/ee2020_with_vga.cache/wt [current_project]
set_property parent.project_path D:/Vivado/Projects/ee2020_with_vga/ee2020_with_vga.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  D:/Vivado/Projects/ee2020_with_vga/ee2020_with_vga.srcs/sources_1/imports/sources_1/imports/new/vga_sync.v
  D:/Vivado/Projects/ee2020_with_vga/ee2020_with_vga.srcs/sources_1/imports/sources_1/new/seven_segment.v
  D:/Vivado/Projects/ee2020_with_vga/ee2020_with_vga.srcs/sources_1/imports/sources_1/new/binary_to_BCD.v
  D:/Vivado/Projects/ee2020_with_vga/ee2020_with_vga.srcs/sources_1/imports/sources_1/new/tirangleLUT.v
  D:/Vivado/Projects/ee2020_with_vga/ee2020_with_vga.srcs/sources_1/imports/sources_1/imports/new/sineLUT.v
  D:/Vivado/Projects/ee2020_with_vga/ee2020_with_vga.srcs/sources_1/imports/sources_1/imports/new/vga_test.v
  D:/Vivado/Projects/ee2020_with_vga/ee2020_with_vga.srcs/sources_1/imports/Downloads/Keyboard.v
  D:/Vivado/Projects/ee2020_with_vga/ee2020_with_vga.srcs/sources_1/imports/sources_1/new/function_gen.v
  D:/Vivado/Projects/ee2020_with_vga/ee2020_with_vga.srcs/sources_1/imports/sources_1/new/dual_gen.v
}
read_vhdl -library xil_defaultlib {
  D:/Vivado/Projects/ee2020_with_vga/ee2020_with_vga.srcs/sources_1/imports/sources_1/imports/hdl/Ps2Interface.vhd
  D:/Vivado/Projects/ee2020_with_vga/ee2020_with_vga.srcs/sources_1/imports/sources_1/imports/hdl/MouseCtl.vhd
  D:/Vivado/Projects/ee2020_with_vga/ee2020_with_vga.srcs/sources_1/imports/sources_1/imports/Downloads/DA2RefComp.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{D:/Vivado/Projects/ee2020_with_vga/ee2020_with_vga.srcs/constrs_1/imports/Laboratory and Project/Basys3_Master.xdc}}
set_property used_in_implementation false [get_files {{D:/Vivado/Projects/ee2020_with_vga/ee2020_with_vga.srcs/constrs_1/imports/Laboratory and Project/Basys3_Master.xdc}}]


synth_design -top dual_gen -part xc7a35tcpg236-1


write_checkpoint -force -noxdef dual_gen.dcp

catch { report_utilization -file dual_gen_utilization_synth.rpt -pb dual_gen_utilization_synth.pb }
